### ISSUE TITLE
Proxy not working

### ISSUE THREAD

**Issue by mkaliyannan** [cookiengineer/adblock-proxy#13]
Hi - As you described I deployed on linux and tried. but seems not working. Where Can I see the log?

I am pretty much intersted this project to add intercept https sites.

**Comment by cookiengineer** [comment]
1. what did you do?
2. Did you follow the [USAGE.md](https://github.com/Artificial-University/adblock-proxy/blob/master/guides/USAGE.md) instructions?
3. Which browser do you use?
4. What are your proxy settings and what host OS do you use?

**Comment by mkaliyannan** [comment]
Yes. I did same instruction. I tested  port is listening too... But no response

**Comment by mkaliyannan** [comment]
or internet activity

**Comment by korovkinand** [comment]
I have the same problem. Tested with XFCE on ubuntu server 16.04 (AWS image)

**Comment by cookiengineer** [comment]
For the sake of completeness:

- I've been busy for the last couple months.
- I've been building a Web Browser instead, because Web Proxies cannot filter out HTTPS-requested URLs and SOCKS is nothing more than a socket-routing-protocol.
- This project is now deprecated, new project is called [stealth-browser](https://github.com/cookiengineer/stealth-browser) which can be used as an ad-blocking Web Proxy, too (among various other features that the new architecture allows).
