### ISSUE TITLE
Cloudflare protected site causes problems

### ISSUE THREAD

**Issue by Moocow9m** [cookiengineer/adblock-proxy#14]
If the site uses cloudflare protection the program causes it to got to a 302 found page and stops... unable to proceed to page.

**Comment by cookiengineer** [comment]
Doh, I have no idea on how to fix this correctly without hacks.

Do you have some cloudflare-hosted URLs that I can test against? As it's a user-config on cloudflare's web UI, the users are responsible for the "how which captcha" is being displayed etc.

**Comment by Moocow9m** [comment]
Well one site would be: kissanime.ru
It runs the cloudflare protection pretty much ever time reliably.

**Comment by cookiengineer** [comment]
For the sake of completeness:

- I've been busy for the last couple months.
- I've been building a Web Browser instead, because Web Proxies cannot filter out HTTPS-requested URLs and SOCKS is nothing more than a socket-routing-protocol.
- This project is now deprecated, new project is called [stealth-browser](https://github.com/cookiengineer/stealth-browser) which can be used as an ad-blocking Web Proxy, too (among various other features that the new architecture allows).
